### ISSUE TITLE
Update to Phoenix 1.7.0

### ISSUE THREAD

**Issue by chargio** [dwyl/phoenix-liveview-counter-tutorial#103]
Followed the tutorial with 1.7.0-rc.0. Here you have the code if you want to use it. Happy to create a PR to the main branch when 1.7 is out. (let me know)

https://github.com/chargio/live_view_counter_test

**Comment by chargio** [comment]
Working on it :D

**Comment by nelsonic** [comment]
@chargio thanks very much for your efforts on this update. 🎉
