### ISSUE TITLE
Initial render renders without styling

### ISSUE THREAD

**Issue by ivymarkwell** [dwyl/phoenix-liveview-counter-tutorial#14]
Hello!

I was recently using your tutorial to update my own application of LiveView because I had found this issue https://github.com/dwyl/phoenix-liveview-counter-tutorial/issues/5 you had opened and was having the same problem.

I noticed that the initial render of the application was still rendering without the styling the exact same way and I believe it is because the root layout is defined as a LiveView layout. Reading the [documentation](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-live-layouts), I believe defining the root layout as a LiveView layout is preventing the initial render to include the styling since the LiveView layouts are rendered after (?), the same way as the initial problem (except before they were never being rendered). I've attached a couple of gifs to better illustrate.

Before:
![before](https://user-images.githubusercontent.com/16991786/78933506-0ad65a80-7a6f-11ea-8155-476ce0346ae0.gif)

After:
![after](https://user-images.githubusercontent.com/16991786/78933516-0dd14b00-7a6f-11ea-908c-eb6c251b9c65.gif)

I fixed this in my own repo by defining the root layout in the router, like: 

```
live "/dashboard", MyApp.Dashboard, layout: {MyApp.LayoutView, :root}
```

and rendering the root layout as a regular `.eex` template. I also of course pulled down y'all's repo and verified this also fixes the same problem. Anyways! I know it's a super minute issue, just wanted to point it out and also to clarify my own understanding of why the problem was happening.

Thanks :)

**Comment by iteles** [comment]
@ivymarkwell This is a great catch and thank you for submitting such a _detailed_ issue 😍 

If you have a chance, we'd love it if you could submit a PR to fix this issue ☺️

**Comment by ivymarkwell** [comment]
@iteles Forked the repo and opened https://github.com/dwyl/phoenix-liveview-counter-tutorial/pull/15

**Comment by ivymarkwell** [comment]
This should be fixed now with https://github.com/dwyl/phoenix-liveview-counter-tutorial/pull/16
