### ISSUE TITLE
Update to Phoenix v1.5.3 and LiveView v0.13.2

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-counter-tutorial#17]
With the release of Phoenix `v1.5.3` and LiveView `v0.13.2` we need to revisit this tutorial and update.

I think we _could_ tackle this update _before_ https://github.com/dwyl/phoenix-chat-example/issues/38 as it's simpler, but equally we can do it _after_. 💭  

This is relevant to our Email https://github.com/dwyl/email project which uses `LiveView`.

**Comment by SimonLab** [comment]
See the upgrade guide: https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f

If you need to first update erlang and elixir using asdf:
- `asdf update` to update asdf itself
- `asdf plugin list` to make sure you have erlang and elixir plugins
- `asdf plugin update erlang` to update the erlang plugin (repeat for elixir)
- `asdf install erlang latest` to install the latest erlang version
- `asdf global erlang <version>` to set the default version of erlang
- `asdf list erlang` to see the list of installed versions

**Comment by nelsonic** [comment]
@SimonLab seems like it's worth adding an intro to `asdf` somewhere. 
e.g: https://github.com/dwyl/dev-setup or https://github.com/dwyl/learn-elixir ?

If people don't have any prior experience with the tool we are introducing them to something they don't _need_ for the tutorial which creates a barrier to entry. Not saying `asdf` is _not_ a good tool, just that it's probably not _necessary_ for _this_ tutorial. But it's totally legit in the toolbelt of an experienced developer. 👍

**Comment by nelsonic** [comment]
https://twitter.com/josevalim/status/1258842121139863554

**Comment by nelsonic** [comment]
PR: #18 🙌

**Comment by BigTom** [comment]
End user here:

Branch seems to work fine for me (master ran but counter did not work).  If that helps?

- Running on macos catalina
- Elixir 1.10.3 (compiled with Erlang/OTP 22)
- Phoenix v1.5.1
- node v14.0.0

**Comment by nelsonic** [comment]
@BigTom thanks for confirming. 🙌

**Comment by nelsonic** [comment]
Update PR #18 reviewed and merged by @SimonLab ✅
