### ISSUE TITLE
Dependency issue in phoenix 1.5.3 project generator

### ISSUE THREAD

**Issue by BigTom** [dwyl/phoenix-liveview-counter-tutorial#19]
Hi,

There is a bug in the phoenix 1.5.3 project generator:
(see: https://elixirforum.com/t/newly-created-app-hangs-on-home-page-with-error-in-phoenix-liveview-channel-start-link-1/31738)

To fix it you need to manually fix the deps (from chrismccord)

> You need to jump to LV 0.13 when running the latest phoenix so adding {:phoenix_live_view, "~> 0.13.0"} and mix deps.get will fix it

Would be good to note this in the readme.

**Comment by nelsonic** [comment]
@BigTom thanks for opening this issue to inform us and others. If you have time, please open a Pull Request to add the info to the README. 👍

**Comment by BigTom** [comment]
Created a PR :-)
Failed to link it back here :-(
First one, by gentle!

**Comment by nelsonic** [comment]
@BigTom PR #20 merged. 📦 
Thanks again! 🥇
