### ISSUE TITLE
Feat: Update to Phoenix LiveView 1.0-rc

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-counter-tutorial#211]
`Phoenix LiveView 1.0-rc` recently released! 🎉 
Ref: https://github.com/dwyl/learn-elixir/issues/216

# Todo

+ [ ] Re-write the tutorial from scratch for the latest version! 🧑‍💻 
+ [ ] Make any necessary updates. ⬆️

**Comment by ndrean** [comment]
PR #217
