### ISSUE TITLE
cd into app folder before running the tests

### ISSUE THREAD

**Issue by iteles** [dwyl/phoenix-liveview-counter-tutorial#22]
Given this is a tutorial for _complete_ beginners, as stated in the intro, it might be worth adding a note to 'Checkpoint 1: Run the Tests!' that you need to cd into the app folder before running them.

If you type `mix test` into the CLI straight after installing the dependencies you'll get:
![image](https://user-images.githubusercontent.com/4185328/84195668-df83e200-aa96-11ea-9d6f-8b0153bd148c.png)

Phoenix is very user-friendly in that it gives you hints straight away if you wanted to run your new app:
![image](https://user-images.githubusercontent.com/4185328/84195533-a77c9f00-aa96-11ea-8641-346e7c2f5450.png)
But if you're brand new to phoenix (and programming), you might miss it.

In your terminal, go into the newly created app folder using:
```sh
cd live_view_counter
```

**Comment by elijose55** [comment]
can I work on this issue?

**Comment by iteles** [comment]
@elijose55 Sure, go ahead, @nelsonic have you a thumbs up 👍🏻

This was part of a larger PR for me which I’m re-basing given the latest changes to the docs. It’s a small one so no problem if you do it instead ☺️
