### ISSUE TITLE
GenServer issue 

### ISSUE THREAD

**Issue by MikeRund** [dwyl/phoenix-liveview-counter-tutorial#220]
When switching to GenServer in the bonus section, I encounter the following error:

`
unhandled exit at GET /
exited in: GenServer.call(:count_server, :current, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
`

My code is the same as the tutorial, and if I check to see if the GenServer is running I get a process ID:

`
iex(1)> Process.whereis(:count_server)
#PID<0.239.0>
`

**Comment by nelsonic** [comment]
@MikeRund are you investigating this? do you need any help? 🧑‍💻

**Comment by ndrean** [comment]
:exclamation: "We are also going to need to tell the Application that it now has some business logic; we do this in the start/2 function in the lib/counter/application.ex file."

```elixir
def start(_type, _args) do
    children = [
      # Start the App State
+     Counter.Count,
       ^^^?
```

**Comment by MikeRund** [comment]
I did already have Counter.Count in my application.ex file. Logging on today and the GenServer appears to be working, with some styling issues. Was a server restart required after moving the state from LiveView to GenServer?

**Comment by nelsonic** [comment]
Yes, a state change of that kind would require a restart. So that "fixed" the problem. 👌

**Comment by nelsonic** [comment]
@MikeRund thanks for both opening, updating and _closing_ this issue. Very good practice in your journey. 🙌
