### ISSUE TITLE
`Map.pop!3` not a recognized function

### ISSUE THREAD

**Issue by MikeRund** [dwyl/phoenix-liveview-counter-tutorial#221]
For adding a presence at the final step of this project I run into an error with `Map.pop!/3`. 

This issue is fixed when using `Map.pop/3`, as of the documentation of elixir 1.17.3 there appears to be `pop/3` or `pop!/2`, where `pop!/2` simply does not return a default map if `key` is not present.

Just checking that this `Map.pop/3` is the correct approach, I'm assuming it is as we pass in a default map when pattern matching:

` {_, joins} = Map.pop!(joins, socket.id, %{})`

**Comment by nelsonic** [comment]
https://hexdocs.pm/elixir/1.12/Map.html#pop/3 👍

**Comment by MikeRund** [comment]
Thanks!
