### ISSUE TITLE
Mac-only error: Can't find executable `mac-listener`

### ISSUE THREAD

**Issue by iteles** [dwyl/phoenix-liveview-counter-tutorial#23]
This error may not be specific to the liveview counter tutorial but I wanted to leave a note here in case anyone else comes across it.

My server was hanging in Step 1, but it wasn't throwing the error mentioned in https://github.com/dwyl/phoenix-liveview-counter-tutorial#problems-getting-the-initial-server-running
It _was_ however throwing this error:
![image](https://user-images.githubusercontent.com/4185328/84404383-a6668180-abfe-11ea-8c9d-eb1e47d026f5.png)

At this stage, I don't know if this will fix the server hanging issue but it's an error that would be useful to be fixed either way.

**Comment by iteles** [comment]
I tried updating XCode but the error remains.

**Comment by iteles** [comment]
Trying this solution next:
https://stackoverflow.com/questions/47645704/elixir-phoenix-live-reload-doesnt-work
![image](https://user-images.githubusercontent.com/4185328/84404908-54722b80-abff-11ea-9604-0f33d7d687f1.png)

**Comment by nelsonic** [comment]
@iteles any luck after updating XCode?

**Comment by iteles** [comment]
Installing the XCode CLI as per the SO answer worked to fix the error in this issue so I'm going to close it.
Server still hanging so going to look at that separately 👍
