### ISSUE TITLE
Broken link for server hanging section

### ISSUE THREAD

**Issue by iteles** [dwyl/phoenix-liveview-counter-tutorial#24]
The link in Step 1 to the troubleshooting section for the server hanging is broken.

It needs to be amended from `try
 [this](###-problems-with-dependencies)` to `try [updating your `deps` as explained in our troubleshooting section](#problems-getting-the-initial-server-running)`

**Comment by nelsonic** [comment]
@iteles if after trying for a few mins you are still stuck, LMK if you want a second pair of eyes. 🤓

**Comment by BigTom** [comment]
I have fixed this in the current open PR.  (Its due to a misunderstanding on my part how the anchor syntax works works, an overgenerous markdown previewer in VSCode and my not double checking at the end 😳.

**Comment by iteles** [comment]
👍 Thanks @BigTom. Updated in PR #21 

I'll go through the tutorial again and will make the quick change as per the OP for the more descriptive link, but great that it's linking correctly now 🙌

**Comment by nelsonic** [comment]
Closing as resolved. ✅
