### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-counter-tutorial#36]
Two years later people still find the tutorial useful: https://twitter.com/mrkurt/status/1362940036795219973
![image](https://user-images.githubusercontent.com/194400/109387184-c8707300-78f7-11eb-9f2f-3a13f5433b77.png)

@mrkurt has deployed the counter to a 17 region cluster using fly.io: https://liveview-counter.fly.dev
![image](https://user-images.githubusercontent.com/194400/109387273-58aeb800-78f8-11eb-92ed-6b2d6de1bec3.png)

Code: https://github.com/fly-apps/phoenix-liveview-cluster/blob/master/lib/live_view_counter_web/live/counter.ex

**Comment by nelsonic** [comment]
https://fly.io/blog/we-are-hiring-elixir-developer-advocates
![image](https://user-images.githubusercontent.com/194400/109429921-69455800-79f6-11eb-8b66-f6c0c4991a9d.png)

**Comment by mrkurt** [comment]
We're also using it as our Elixir hiring project: https://github.com/superfly/elixir-hiring-project#flyio-elixir-hiring-project

This may have the most thorough readme I've ever seen.

**Comment by nelsonic** [comment]
Hi @mrkurt! 👋  
We saw your Elixir hiring project; it's right up our street! 😍 
We have quite a few beginner-friendly Elixir/Phoenix projects/tutorials with similar docs: [github.com/dwyl?language=elixir](https://github.com/dwyl?language=elixir) 
I think that between us @dwyl could _easily_ be your Elixir Dev Advocate. :wink:

**Comment by nelsonic** [comment]
Included in #70
