### ISSUE TITLE
Finished project broken

### ISSUE THREAD

**Issue by leephillips** [dwyl/phoenix-liveview-counter-tutorial#44]
The finished project does not work on my machine (Debian 10). After entering `mix phx.server` I was prompted to install rebar3, which I did. Entering `mix phx.server` gets me this error:

    function :crypto.hmac/3 is undefined or private

**Comment by doesnotexist** [comment]
Works for me after running:
`mix deps.update --all`

In my case I think the VS-Code Elixir-LS had autoinstalled some packages and picked up a version of plug depends on :crypto.hmac/3  and then updating all the installed dependencies fixed that.  Completely new to elixir so thats a little bit of a guess based on what I found googling the error and remembering that Elixir-LS prompted me about installing packages prior to my first run of the livecounter repo.

**Comment by nelsonic** [comment]
We have comprehensively updated the tutorial including all dependencies in our 2022 Update: #70 ⬆️ 
This should no longer be an issue for anyone **`new`** reading this in 2022. 🤞
