### ISSUE TITLE
Update "Create the App" section

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-liveview-counter-tutorial#52]
With Phoenix 1.6 the --live option is not required as the new application contains all the files necessary by default for a live application.
Existing options (https://hexdocs.pm/phoenix/Mix.Tasks.Phx.New.html or `mix help phx.new`)
![image](https://user-images.githubusercontent.com/6057298/138660905-69cc2f72-ea2a-4be3-99bb-1f1d374591b6.png)

We can see instead that there is a --no-live option if the application is not "live"

**Comment by nelsonic** [comment]
Included in #70
