### ISSUE TITLE
npm install --prefix assets error on windows 10

### ISSUE THREAD

**Issue by vapidbabble** [dwyl/phoenix-liveview-counter-tutorial#8]
\Projects\elixir\phoenix>elixir -v
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.10.2 (compiled with Erlang/OTP 21)

\Projects\elixir\phoenix>mix phx.new -v
Phoenix v1.4.15

\Projects\elixir\phoenix>node -v
v12.16.1

after cloning and mix deps.get successfully I attempt 
npm install --prefix assets 
and  I get 
\Projects\elixir\phoenix\phoenix-liveview-counter-tutorial>npm install --prefix assets
npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     
\AppData\Roaming\npm-cache\_logs\2020-03-12T16_40_00_067Z-debug.log

[2020-03-12T16_40_00_067Z-debug.log](https://github.com/dwyl/phoenix-liveview-counter-tutorial/files/4325431/2020-03-12T16_40_00_067Z-debug.log)

**Comment by nelsonic** [comment]
Hi @vapidbabble, thanks for opening the issue!
Out of curiosity, how/where did you discover the tutorial? 

On Windows, please try:
```
cd assets && npm install
cd ..
```

We may need to add this to the `README.md` as per the official instructions:
https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/introduction/installation.md
![image](https://user-images.githubusercontent.com/194400/76546032-b1383b80-6482-11ea-846b-1f48aca225be.png)

**Comment by nelsonic** [comment]
@vapidbabble were you able to make progress on your quest? 💭
